# markdownlint config

# MD013/line-length: disable line length for all. We prefer lines as
# long as paragraph with in-editor line breaks.
MD013: false

MD025:
  front_matter_title: ""

# MD033/no-inline-html
MD033: false

# MD045/no-alt-text
MD045: false

# MD046/code-block-style: code block style conflicting with
# admonitions...
MD046: false

# MD048/code-fence-style: code fence style
MD048:
  style: backtick
